// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Todo struct {
	ID          string
	Title       string
	Description string
	Done        bool
	CreatedAt   time.Time
}
