POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Estudar Flutter",
  "description": "Documentação sobre custom painter"
}

###

GET http://localhost:8080/todos

###
GET http://localhost:8080/todos/b575f812-c33b-488b-900b-088d48afee4a

###

PUT http://localhost:8080/todos/b575f812-c33b-488b-900b-088d48afee4a
Content-Type: application/json

{
  "title": "Estudar Golang",
  "description": "Ler Documentação sobre GO",
  "done": true
}

###

DELETE http://localhost:8080/todos/b575f812-c33b-488b-900b-088d48afee4a

